Vagrant.configure("2") do |config|
    config.vm.box = "opentable/win-2012r2-standard-amd64-nocm"
    config.vm.box_version = "1.0.0"
    config.vm.hostname = "URSA"
    config.vm.network "public_network"
    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = 4096
        vb.cpus = 4
        vb.name = "URSA"
    end
end
